CREATE TABLE CUSTOMER
(
    ID UUID NOT NULL,
    CUSTOMER_NBR VARCHAR NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IDX_U_CUSTOMER_CUSTOMER_NBR ON CUSTOMER (CUSTOMER_NBR);