CREATE TABLE ORDERS
(
    ID UUID NOT NULL,
    ORDER_NBR VARCHAR NOT NULL,
    ORDER_TEXT VARCHAR NOT NULL,
    CUSTOMER_ID UUID NOT NULL,
    CONSTRAINT PK_ORDER_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_TO_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (ID)
);
CREATE UNIQUE INDEX IDX_U_ORDER_ORDER_NBR ON ORDERS (ORDER_NBR);
